version: '3'

services:
  python-server:
    build: ./python-server
    container_name: python-server
    ports:
      - "5006:5006"

  node-server:
    build: ./node-server
    container_name: node-server
    depends_on:
      - database
      - python-server
    ports:
      - "3006:3006"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=conversation

  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_DB: conversation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
